all: makefile

# The cellblender/extensions directory is a common location to place
# applications related to (but not part of) CellBlender.
# This provides a common location for applications bundled with CellBlender.

clean: makefile
