par_list={
   1:{'name':"Nav",'value':"6.022e8",'unit':"",'type':"Avogadro number for 1 um^3"},
   2:{'name':"rxn_layer_t",'value':"0.01",'unit':"um",'type':""},
   3:{'name':"vol_wall",'value':"0.88/rxn_layer_t",'unit':"um^2",'type':""},
   4:{'name':"vol_EC",'value':"39",'unit':"um^3",'type':""},
   5:{'name':"vol_PM",'value':"0.01/rxn_layer_t",'unit':"um^2",'type':""},
   6:{'name':"vol_CP",'value':"1",'unit':"um^3",'type':""},
   7:{'name':"kp1",'value':"0.000166057788110262*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   8:{'name':"km1",'value':"0.00",'unit':"/s",'type':"Unimolecular reaction"},
   9:{'name':"kp2",'value':"1.66057788110262e-06/rxn_layer_t",'unit':"um^2/#.s",'type':"Bimolecular reaction"},
   10:{'name':"km2",'value':"0.00",'unit':"/s",'type':"Unimolecular reaction"},
   11:{'name':"kpL",'value':"0.0166057788110262/rxn_layer_t",'unit':"um^2/#.s",'type':"Bimolecular reaction"},
   12:{'name':"kmL",'value':"20",'unit':"/s",'type':"Unimolecular reaction"},
   13:{'name':"kpLs",'value':"0.0166057788110262/rxn_layer_t",'unit':"um^2/#.s",'type':"Bimolecular reaction"},
   14:{'name':"kmLs",'value':"0.12",'unit':"/s",'type':"Unimolecular reaction"},
   15:{'name':"kpS",'value':"0.0166057788110262*Nav",'unit':"/M.s",'type':"Bimolecular reaction"},
   16:{'name':"kmS",'value':"0.13",'unit':"/s",'type':"Unimolecular reaction"},
   17:{'name':"pLb",'value':"30",'unit':"/s",'type':"Unimolecular reaction"},
   18:{'name':"pLbs",'value':"100",'unit':"/s",'type':"Unimolecular reaction"},
   19:{'name':"pLg",'value':"1",'unit':"/s",'type':"Unimolecular reaction"},
   20:{'name':"pLgs",'value':"3",'unit':"/s",'type':"Unimolecular reaction"},
   21:{'name':"pLS",'value':"30",'unit':"/s",'type':"Unimolecular reaction"},
   22:{'name':"pLSs",'value':"100",'unit':"/s",'type':"Unimolecular reaction"},
   23:{'name':"pSS",'value':"100",'unit':"/s",'type':"Unimolecular reaction"},
   24:{'name':"pSSs",'value':"200",'unit':"/s",'type':"Unimolecular reaction"},
   25:{'name':"dm",'value':"0.1",'unit':"/s",'type':"Unimolecular reaction"},
   26:{'name':"dc",'value':"0.1",'unit':"/s",'type':"Unimolecular reaction"},
   27:{'name':"Lig_tot",'value':"6.0e3",'unit':"Number",'type':""},
   28:{'name':"Rec_tot",'value':"4.0e2",'unit':"Number",'type':""},
   29:{'name':"Lyn_tot",'value':"2.8e2",'unit':"Number",'type':""},
   30:{'name':"Syk_tot",'value':"4e2",'unit':"Number",'type':""},
   31:{'name':"T",'value':"298.25",'unit':"K",'type':""},
   32:{'name':"h",'value':"rxn_layer_t",'unit':"um",'type':""},
   33:{'name':"Rs",'value':"0.002564",'unit':"um",'type':""},
   34:{'name':"Rc",'value':"0.0015",'unit':"um",'type':""},
   35:{'name':"gamma",'value':"0.5722",'unit':"",'type':"Euler's constant"},
   36:{'name':"KB",'value':"1.3806488e-19",'unit':"cm^2.kg/K.s^2",'type':"Boltzmann constant"},
   37:{'name':"mu_wall",'value':"1e-9",'unit':"kg/um.s",'type':"viscosity"},
   38:{'name':"mu_EC",'value':"1e-9",'unit':"kg/um.s",'type':"viscosity"},
   39:{'name':"mu_PM",'value':"1e-9",'unit':"kg/um.s",'type':"viscosity"},
   40:{'name':"mu_CP",'value':"1e-9",'unit':"kg/um.s",'type':"viscosity"}}

mol_list={
   1:{'name':"s1",'type':"3D",'dif':"KB*T/(6*PI*mu_EC*Rs)"},
   2:{'name':"s2",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   3:{'name':"s3",'type':"3D",'dif':"KB*T/(6*PI*mu_CP*Rs)"},
   4:{'name':"s4",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   5:{'name':"s5",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   6:{'name':"s6",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   7:{'name':"s7",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   8:{'name':"s8",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(2)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   9:{'name':"s9",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(3)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"},
   10:{'name':"s10",'type':"2D",'dif':"KB*T*LOG((mu_PM*h/(SQRT(4)*Rc*(mu_EC+mu_CP)/2))-gamma)/(4*PI*mu_PM*h)"}}

rxn_list={
   1:{'reactants':"s4' + s1'",'products':"s5'",'fwd_rate':"2*kp1"},
   2:{'reactants':"s4' + s2'",'products':"s6'",'fwd_rate':"kpL"},
   3:{'reactants':"s6' + s1'",'products':"s7'",'fwd_rate':"2*kp1"},
   4:{'reactants':"s5'",'products':"s4' + s1'",'fwd_rate':"km1"},
   5:{'reactants':"s4' + s5'",'products':"s8'",'fwd_rate':"kp2"},
   6:{'reactants':"s6' + s5'",'products':"s9'",'fwd_rate':"kp2"},
   7:{'reactants':"s5' + s2'",'products':"s7'",'fwd_rate':"kpL"},
   8:{'reactants':"s6'",'products':"s4' + s2'",'fwd_rate':"kmL"},
   9:{'reactants':"s7'",'products':"s6' + s1'",'fwd_rate':"km1"},
   10:{'reactants':"s4' + s7'",'products':"s9'",'fwd_rate':"kp2"}}

rel_list={
   1:{'name':"Release_Site_s1",'molecule':"s1",'shape':"OBJECT",'orient':",",'quantity_type':"DENSITY",'quantity_expr':"Lig_tot/(Nav*vol_EC)",'object_expr':"EC[ALL] - CP[ALL]"},
   2:{'name':"Release_Site_s2",'molecule':"s2",'shape':"OBJECT",'orient':"\'",'quantity_type':"DENSITY",'quantity_expr':"Lyn_tot/vol_PM",'object_expr':"CP[PM]"},
   3:{'name':"Release_Site_s3",'molecule':"s3",'shape':"OBJECT",'orient':",",'quantity_type':"DENSITY",'quantity_expr':"Syk_tot/(Nav*vol_CP)",'object_expr':"CP"},
   4:{'name':"Release_Site_s4",'molecule':"s4",'shape':"OBJECT",'orient':"\'",'quantity_type':"DENSITY",'quantity_expr':"Rec_tot/vol_PM",'object_expr':"CP[PM]"}}
